accounts/urls.py
from django.urls import path,include
from . import views

app_name='accounts'

urlpatterns = [
    path('signup',views.signup,name='sign_up'),
    path('profile',views.profile,name='profile'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
]

contact/urls.py
from django.urls import path,include
from . import views

app_name='contact'

urlpatterns = [
    path('',views.send_massage,name='contact'),
]

job/urls.py
from django.urls import path,include
from . import views
from . import api

app_name='job'

urlpatterns = [
    path('',views.job_list,name='job_list'),
    path('add',views.jop_add,name='add_job'),
    path('<str:slug>',views.job_detail,name='job_details'),

    # api
    path('api/jobs',api.joblistapi,name='job_list_api'),
    path('api/jobs/<int:id>',api.job_detail_api,name='job_detail_api'),

    #CBV
    path('api/v2/jobs',api.JobListApi.as_view(),name='Job_List_Api'),
    path('api/v2/jobs/<int:id>',api.JobDetail.as_view(),name='Job_Detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('job.urls',namespace="jobs")),
    path('contact-us/', include('contact.urls',namespace="contact")),
    path('api-auth/', include('rest_framework.urls')),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



# Create your models here.
class City(models.Model):
    name=models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    city=models.ForeignKey('City', related_name="user_city", on_delete=models.CASCADE, null=True,blank=True)
    phone_number=models.CharField(max_length=15)
    image=models.ImageField(upload_to='profile/')

    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
    

contact/models.py
from django.db import models

# Create your models here.

class Info(models.Model):
    place=models.CharField(max_length=50)
    phone_number=models.CharField(max_length=20)
    email=models.EmailField(max_length=100)

    

    class Meta:
        verbose_name = ("Info")
        verbose_name_plural = ("Infos")

    def __str__(self):
        return self.email

home/models.py
from django.db import models

# Create your models here.

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.

job_type=(
    ('Full Time','Full Time'),
    ('Part Time','Part Time'),
)

class Category(models.Model):
    name=models.CharField(max_length=25)

    def __str__(self):
        return self.name

def image_upload(instance,filename):
    imagename, extension=filename.split(".")
    return "jobs/%s.%s"%(instance.title,extension)

class job(models.Model):
    owner = models.ForeignKey(User, related_name="job_owner", on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    slug=models.SlugField(null=True,blank=True)
    #location
    job_type=models.CharField(max_length=15, choices=job_type)
    description=models.TextField(max_length=1000)
    published_at=models.DateTimeField(auto_now=True)
    vacancy=models.IntegerField(default=1)
    salary=models.IntegerField(default=0)
    experience=models.IntegerField(default=1)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to=image_upload)

    def save(self,*args, **kwargs):
        self.slug=slugify(self.title)
        super(job,self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    
class Apply(models.Model):
    job=models.ForeignKey(job, related_name='apply_job', on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    email=models.EmailField(max_length=100)
    website=models.URLField()
    cv=models.FileField(upload_to='apply/')
    cover_later=models.TextField(max_length=500)
    created_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render,redirect
from .form import SignUpForm,UserForm,ProfileForm
from django.contrib.auth import authenticate,login
from .models import Profile
from django.urls import reverse
# Create your views here.
def signup(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('accounts/profile')
    else:
        form=SignUpForm()
    return render(request,'registration/signup.html',{'form':form})

def profile(request):
    profile=Profile.objects.get(user=request.user)

    return render(request,'accounts/profile.html',{'profile':profile})


def profile_edit(request):
    profile=Profile.objects.get(user=request.user)
    if request.method=='POST':
        userform=UserForm(request.POST,instance=request.user)
        profileform=ProfileForm(request.POST,request.FILES,instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile=profileform.save(commit=False)
            myprofile.user=request.user
            myprofile.save()
            return redirect(reverse('accounts:profile'))
    else:
        userform=UserForm(instance=request.user)
        profileform=ProfileForm(instance=profile)
    return render(request,'accounts/profile_edit.html',{'userform':userform,'profileform':profileform})

contact/views.py
from django.shortcuts import render
from .models import Info
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.

def send_massage(request):
    myinfo=Info.objects.first()
    if request.method=='POST':
        subject=request.POST['subject']
        email=request.POST['email']
        message=request.POST['message']

        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [email],
        )
    return render(request,'contact/contact.html',{'myinfo':myinfo})

home/views.py
from django.shortcuts import render

# Create your views here.

job/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from .models import job
from .form import Applyform ,JobForm
from django.contrib.auth.decorators import login_required
from .filters import JobFilter


# Create your views here.
def job_list(request):
    job_list=job.objects.all()

    myfilter=JobFilter(request.GET,queryset=job_list)
    job_list=myfilter.qs

    paginator=Paginator(job_list,3)
    page_number=request.GET.get('page')
    page_obj= paginator.get_page(page_number)
    cotext={'jobs':page_obj,'myfilter':myfilter}
    return render(request,"job/job_list.html",cotext)

def job_detail(request, slug):
    job_detail=job.objects.get(slug=slug)
    if request.method=='POST':
        form=Applyform(request.POST,request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.job=job_detail
            myform.save()
    else:
        form = Applyform()


    cotext={'job':job_detail,'form': form}
    return render(request,"job/job_details.html",cotext)

@login_required
def jop_add(request):

    if request.method=='POST':
        form=JobForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.owner=request.user
            myform.save()
            return redirect(reverse('jobs:job_list'))
        
    else:
        form=JobForm()
    
    

    return render(request,"job/add_job.html",{'form':form})

accounts/templates/accounts/profile.html
{% extends "base.html" %} 
{% load django_bootstrap5 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{ job }}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>
                            </ul>
                             
                        </div>
                        <div class='p-5'>
                           <center> <a class="boxed-btn3 w-100 mb-2" href="{% url 'accounts:profile_edit' %}" >Edit Profile</a></center> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends "base.html" %} 
{% load django_bootstrap5 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form  method="POST" enctype="multipart/form-data">
                            {% csrf_token %}

                            {% bootstrap_form userform %}
                            {% bootstrap_form profileform %}

                            {% bootstrap_button button_type="submit" content="Save" extra_classes="boxed-btn3 w-100 mb-2" %} 
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

contact/templates/contact/contact.html
{% extends "base.html" %}

{% block body %}

    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>contact</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>


  <section class="contact-section section_padding">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Get in Touch</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form" method="post" >
            {% csrf_token %}
            <div class="row">

              <div class="col-12">
                <div class="form-group">
                  <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder = 'Enter Subject'>
                </div>
              </div>

                <div class="col-sm-12">
                    <div class="form-group">
                      <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder = 'Enter email address'>
                    </div>
                  </div>

              <div class="col-12">
                <div class="form-group">
                    <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder = 'Enter Message'></textarea>
                </div>
              </div>
            </div>
            <div class="form-group mt-3">
              <button type="submit" class="button button-contactForm btn_4 boxed-btn">Send Message</button>
            </div>
          </form>
        </div>
        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>{{myinfo.place}}</h3>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>{{myinfo.phon_numer}}</h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>{{myinfo.email}}</h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock body %}

job/templates/job/job_list.html
{% extends "base.html" %} 
{% load django_bootstrap5 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs.count}}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form myfilter.form %}
                                <input type="submit" value="Search" class="boxed-btn3 w-100 mt-4">
                            </form>
                        </div>
                        {% comment %} <div class="reset_btn">
                            <button  class="boxed-btn3 w-100" type="submit">Reset</button>
                        </div> {% endcomment %}
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in jobs %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_details' job.slug %}"><h4>{{job}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_details' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{ job.published_at|date:'d M o' }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if jobs.has_previous %}
                                            <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in jobs.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if jobs.has_next %}
                                            <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}

templates/base.html
{%load static%}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="/">home</a></li>
                                            <li><a href="{% url 'jobs:job_list' %}">Browse Job</a></li>
                                            <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    {% if request.user.is_authenticated %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'accounts:profile' %}">Profile</a>
                                        </div>
                                    {% else %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'login' %}">Log in</a>
                                        </div>
                                    {% endif %}
                                    
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{% url 'jobs:add_job' %}">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {% block body %} {% endblock body %}

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br>
                                +10 873 672 6782 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- <script src="{% static 'js/gijgo.min.js' %}"></script> -->
    <script src="{% static 'js/range.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/main.js' %}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>

templates/base_generic.html
{% extends "base.html" %} 
{% load django_bootstrap5 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
     
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        {% block content %}
                        
                        {% endblock content %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}